artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: vbookshelf/rice-leaf-diseases
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_model:
  root_dir: artifacts/prepare_model
  model_path: artifacts/prepare_model/model.keras

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.keras

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras
